# Generated by Django 4.2.20 on 2025-03-11 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
