# Generated by Django 4.2.20 on 2025-03-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_fraudulent',
            field=models.BooleanField(default=False),
        ),
    ]
